default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

common: &common
  <<: *default
  host: <%= ENV["DB_HOST"] || "localhost" %>
  username: <%= ENV["DB_USER"] || "root" %>
  password: <%= ENV["DB_PASS"] || "" %>
  socket: <%= ENV["DB_SOCKET"] || "/tmp/mysql.sock" %>
  pool: <%= ENV["DB_POOL"] || 5 %>

development:
  <<: *common
  database: ipo-juku_development

test:
  <<: *common
  database: ipo-juku_test

staging:
  <<: *common
  database: <%= ENV["DB_NAME"] %>

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>